# Use an official GCC image as a parent image
FROM gcc:latest

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install necessary libraries
RUN apt-get update && \
	apt-get upgrade && \
	apt-get install -y libc6 libc6-dev libldap-dev libssl-dev

# Run make with the target 'server'
RUN make all

# Run the application
CMD ["./bin/server", "6543", "spool"]